// src/routes/help/+page.svelte
<div class="readme px-6 py-8 font-sans text-gray-800 sm:px-10 dark:text-gray-200">
    <div class="readmeDiv space-y-10">
        <div>
            <h1 class="mb-6 text-4xl font-bold text-slate-700 sm:text-5xl dark:text-slate-300">
                How to add your Zig library to Zigistry?
            </h1>
            <div class="space-y-4 text-lg sm:text-xl">
                <ol class="ml-8 list-decimal space-y-3 sm:ml-12">
                    <li>
                        On the main page of your GitHub repository, click on the <strong
                            class="text-slate-600 dark:text-slate-400">Cog wheel icon</strong
                        > on the right of the screen.
                    </li>
                    <li>
                        You'll see a section named <strong
                            class="text-slate-600 dark:text-slate-400">topics</strong
                        > , click on it.
                    </li>
                    <li>
                        Then in the text field, type <strong
                            class="text-slate-600 dark:text-slate-400">zig-package</strong
                        >
                        , press <span class="text-emerald-600 dark:text-emerald-400">enter</span> (or
                        return), and click save changes.
                    </li>
                    <!-- Important! Then create any commit and push. -->
                    <li>
                        <strong class="text-slate-600 dark:text-slate-400"> Important!</strong> Once
                        you have completed the steps above, your repository will be indexed
                        <u>on your next push</u>.
                    </li>
                    <li>
                        And congrats! Your library will be added to Zigistry! <span class="italic"
                            >(Zigistry will register your library in an hour).</span
                        >
                    </li>
                    <li>
                        <iframe
                            class="my-5 h-40 w-48 rounded-xl border-2 border-gray-300 sm:w-80 dark:border-gray-700"
                            width="996"
                            height="521"
                            src="https://www.youtube.com/embed/8iedG5WDv1I?controls=0"
                            title="How to add your Zig package to Zigistry?"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            referrerpolicy="strict-origin-when-cross-origin"
                            allowfullscreen=""
                        ></iframe>
                    </li>
                    <li>
                        Still facing issues or have suggestions? Feel free to open an issue <a
                            class="text-slate-600 underline dark:text-slate-400"
                            href="https://github.com/RohanVashisht1234/zigistry/issues">here</a
                        > .
                    </li>
                </ol>
            </div>
        </div>
        <div>
            <h1 class="mb-6 text-4xl font-bold text-slate-700 sm:text-5xl dark:text-slate-300">
                How to add your Zig program to Zigistry?
            </h1>
            <div class="space-y-4 text-lg sm:text-xl">
                <ol class="ml-8 list-decimal space-y-3 sm:ml-12">
                    <li>
                        The same steps as above, but this time the topic would be <strong
                            class="text-slate-600 dark:text-slate-400">Zig</strong
                        >
                        and not
                        <strong class="text-slate-600 dark:text-slate-400">zig-package</strong> .
                    </li>
                </ol>
            </div>
        </div>
        <div class="hidden lg:block">
            <img
                src="/zigister-finds-repos.svg"
                alt="Zigister finds repos"
                class="w-full rounded-xl border border-gray-300 shadow-md dark:border-gray-700"
                loading="eager"
                width="1200"
                height="900"
                decoding="async"
            />
        </div>
    </div>
</div>

// pages/help.tsx
//!===============================================================
//!                     Help Page "/help"
//!===============================================================
//!	Author  : Rohan Vashisht
//! License : Please check license file
//! Details : This is the default help page which shows how
//! you can add your libraries/programs to Zigistry.
//!===============================================================

// ===================
//       Imports
// ===================

// ------- Components ---------
import Link from "next/link";

// ==========================
//       Exports "/help"
// ==========================
export default function Help() {
  return (
    <>
      <div className="readme">
        <div className="readmeDiv">
          <div className="flex">
            <div>
              <h1 className="text-5xl mb-4">
                How to add your Zig library to Zigistry?
              </h1>
              <div className="text-xl">
                <ol>
                  <li>
                    On the main page of your GitHub repository, click on the Cog
                    wheel icon on the right of the screen
                  </li>
                  <li>You&apos;ll see a section named topics, click on it.</li>
                  <li>
                    Then in the text field type <strong>zig-package</strong>,
                    press enter (or return) and click save changes.
                  </li>
                  <li>
                    And congrats! your library will be added to zigistry!
                    (zigistry will register your library in an hour).
                  </li>
                  <li>
                    <video
                      controls
                      className="rounded-2xl my-5 sm:w-2/5 w-4/5"
                      src="https://github.com/RohanVashisht1234/zigistry/assets/81112205/962b147c-16ce-44d8-a958-57c0f0e1447b"
                    ></video>
                  </li>
                  <li>
                    Still facing issues or have suggestions? feel free to open
                    an issue{" "}
                    <Link
                      className="text-blue-400 underline"
                      href="https://github.com/RohanVashisht1234/zigistry/issues"
                    >
                      here
                    </Link>
                    .
                  </li>
                </ol>
              </div>
            </div>
            <div className="w-full sm:invisible md:invisible lg:visible xl:visible invisible">
              <img className="w-full" src="zigister-finds-repos.svg" />
            </div>
          </div>
          <br />
          <h1 className="text-5xl mb-4">
            How to add your Zig program to Zigistry?
          </h1>
          <div>
            <ol>
              <li>
                The same steps as above but this time the topic would be{" "}
                <strong>Zig</strong> and not Zig-package.
              </li>
            </ol>
          </div>
        </div>
      </div>
      <div className="w-full">
        <img className="w-full" src="zigister-finds-programs.svg" />
      </div>
    </>
  );
}
