// pages/about.tsx
import { BsFillLightningChargeFill } from "react-icons/bs";

export default function About() {
    return (
        <div className="flex items-center justify-center" style={{ height: "calc(100vh - 122px)" }}>
            <div className="">
                <span className="self-center italic whitespace-nowrap dark:text-white text-5xl font-extrabold flex">
                    <span className="text-yellow-300 flex"><BsFillLightningChargeFill />Zig</span>istry
                </span>
                <h2 className="text-2xl italic mt-2">A place where you can find all the libraries that suit your Zig lang needs.</h2>
                <h3 className="text-2xl text-right italic">- Rohan Vashisht</h3>
            </div>
        </div>
    )
}

// src/routes/about/+page.svelte
<div class="flex h-[calc(100vh-122px)] items-center justify-center">
    <div>
        <span
            class="flex self-center text-5xl font-extrabold whitespace-nowrap italic dark:text-white"
            ><span class="flex text-yellow-300"
                ><svg
                    stroke="currentColor"
                    fill="currentColor"
                    stroke-width="0"
                    viewBox="0 0 16 16"
                    height="1em"
                    width="1em"
                    xmlns="http://www.w3.org/2000/svg"
                    ><path
                        d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"
                    ></path></svg
                > Zig</span
            > istry</span
        >
        <h2 class="mt-2 text-2xl italic">
            A place where you can find all the libraries and programs that suit your Zig lang needs.
        </h2>
        <h3 class="text-right text-2xl italic">- Rohan Vashisht</h3>
    </div>
</div>
